# Node docker image on which this would be run
image: node:12.18.4

cache:
  paths:
    - node_modules/

stages:
  - release

# Job 1:
Install:
  stage: release
  environment: production
  script:
    - npm install
    - node_modules/.bin/sequelize db:migrate
    - node_modules/.bin/sequelize db:seed:all

# Job 2:
# Deploy to staging
Production:
  image: ruby:latest
  only:
    - master
  stage: release
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_NAME --api-key=$HEROKU_API
